local mapa = {
    ambient="0.1,0.1,0.1",
    gravity="0 -9.8 0",
    entities={
        {
            name="Camera",
            id=1,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                camera={
                    near="0.1",
                    far="1000",
                    autoaspect="true",
                    aspect="1.78",
                    fov="50",
                    proyection="1",
                    viewport="0,0,1,1",
                    color="0,0,0"
                }
            }
        },
        {
            name="BotonJ",
            id=2,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                button={
                    text="",
                    position="0.43,0.35",
                    size="240,100",
                    name="botonJugar",
                    properties="NormalImage,TaharezLook/ButtonJugar,HoverImage,TaharezLook/ButtonJugarHover,PushedImage,TaharezLook/ButtonJugarPushed",
                    type="CHANGE_SCENE",
                    showCursor="true",
                    cursorImage="TaharezLook/MouseGeorgi",
                    continueBullet="true",
                    nextScene="puzzle1.lua"
                }
     	    }
        },
        {
            name="BotonO",
            id=3,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                button={
                    text="",
                    position="0.43,0.50",
                    size="240,100",
                    name="botonOpciones",
                    properties="NormalImage,TaharezLook/ButtonControles,HoverImage,TaharezLook/ButtonControlesHover,PushedImage,TaharezLook/ButtonControlesPushed",
                    type="CHANGE_SCENE",
                    showCursor="true",
                    cursorImage="TaharezLook/MouseGeorgi",
                    continueBullet="true",
                    nextScene="menucontroles.lua"
                }
     	    }
        },
        {
            name="BotonN",
            id=4,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                button={
                    text="",
                    position="0.43,0.65",
                    size="240,100",
                    name="botonNiveles",
                    properties="NormalImage,TaharezLook/ButtonNiveles,HoverImage,TaharezLook/ButtonNivelesHover,PushedImage,TaharezLook/ButtonNivelesPushed",
                    type="CHANGE_SCENE",
                    showCursor="true",
                    cursorImage="TaharezLook/MouseGeorgi",
                    continueBullet="true",
                    nextScene="menuniveles.lua"
                }
     	    }
        },
        {
            name="BotonS",
            id=5,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                button={
                    text="",
                    position="0.43,0.80",
                    size="240,100",
                    name="botonSalir",
                    properties="NormalImage,TaharezLook/ButtonSalir,HoverImage,TaharezLook/ButtonSalirHover,PushedImage,TaharezLook/ButtonSalirPushed",
                    type="EXIT",
                    showCursor="true",
                    cursorImage="TaharezLook/MouseGeorgi",
                    continueBullet="false",
                    nextScene=""
                }
     	    }
        },
        {
            name="skyBox",
            id=6,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },        
                skybox={
                    enable="true",
                    planenormal="Z",
                    planepos="20",
                    materialname="sky/space",
                    scale="1",
                    tiling="1",
                    drawfirst="true",
                    bow="10.0",
                    xsegments="10",
                    ysegments="10"
                }
            }
        },
        {
            name="Imagen",
            id=7,
            components={
                transform={
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                image={
                    source="TaharezLook/Ogrecabezas",
                    position="0.32,0.1",
                    size="650,130",
                    name="Titulo",
                    properties="BackgroundEnabled,false,FrameEnabled,false,Image,TaharezLook/Ogrecabezas"
                }
            }
        },
        {
            name="musicBox",
            id=8,
            components={
                transform={
                position="0,0,0",
                rotation="0,0,0",
                scale="1,1,1",
                parent="-1"
                },
                musicplayer={
                },
                audiosource={
                sound="TremLoadingloopl.wav",
                volume="0.125",
                velocity="0,0,0"
                }
            }
        }
    }
}

function GetMapa ()
    return mapa
  end